project_id = "mlgciljvegmfirpmnqef"

[functions.teaching-assistant]
verify_jwt = false

[functions.extract-document]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.generate-document]
verify_jwt = false

[functions.generate-syllabus]
verify_jwt = false

[functions.extract-chapters]
verify_jwt = false

[functions.extract-chat-file]
verify_jwt = false

[functions.send-quiz-email]
verify_jwt = false
